# Generated by Django 5.2.15 on 2026-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
